Fix syntax errors in rvfi_csrw_check.sv
	`csrget(`RISCV_FORMAL_CSRW_NAME, rmask)
Got expanded into:
	rvfi.csr_mcycle_ rmask

Because of the extra space, this resulted in:
	[csrw_mcycle_ch0] base: rvfi_csrw_check.sv:56:
		ERROR: syntax error, unexpected TOK_ID